---
# set_SELINUX_to_disabled/tasks/main.yml

- name: 'Set SELINUX state to disabled'
  ansible.posix.selinux:
    state: 'disabled'
    policy: "{{ selinux_policy }}"
  notify:
    - 'Reboot'
    - 'Wait for the machine(s) to be ready again'

- name: 'Flush handlers to trigger reboot now'
  ansible.builtin.meta: flush_handlers

- name: 'Check output of getenforce after reboot'
  ansible.builtin.command: 'getenforce'
  register: 'getenforce_output'
  failed_when: '"Disabled" not in getenforce_output.stdout'
  changed_when: 'false'
